### ISSUE TITLE
Add GPU to network

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad-docs#31]
If possible, record and add a summarized write-up (in case people ask in #help), eventually we do want a proper tutorial.

cc/
@developersteve 

@noryev this is urgent because I want you to work on other stuff, so let's get this off your plate asap.

**Comment by noryev** [comment]
Internal instructions and notes on process: https://docs.google.com/document/d/1XpGcSanAj1sjZNVQVLJ_C7P0V1-wXnVbv3DnsAhTHL8/edit

**Comment by noryev** [comment]
![Image](https://github.com/Lilypad-Tech/lilypad-docs/assets/30084404/1109c61b-f01b-4273-b434-140e3d4be6cb)



![Image](https://github.com/Lilypad-Tech/lilypad-docs/assets/30084404/46c1005a-8a77-4bcb-ade3-f1d6fe62ffc4)

**Comment by noryev** [comment]
Bacalhau and Lilypad Resource Provider both setup and running as systemd daemons

**Comment by noryev** [comment]
Now all i need to do is correctly setup the rpc url and the rest of the network configuration

**Comment by AquiGorka** [comment]
@noryev let's start using Notion for internal drafts until we make them public

**Comment by noryev** [comment]
![Image](https://github.com/Lilypad-Tech/lilypad-docs/assets/30084404/e95d7dfc-38a5-47ff-a791-fbb2765577cd)

**Comment by noryev** [comment]
The instructions were pretty straight forward BUT the Bacalhau and Lilypad install versions all need to be updated!

**Comment by AquiGorka** [comment]
@developersteve I'm adding a card with your name on it to update those instructions

**Comment by Zorlin** [comment]
@noryev Please use Bacalhau v1.2.3 not v1.2.0 for your node

Cheers! (and sorry this wasn't specified anywhere 😢 )
