### ISSUE TITLE
Update Bacalhau and Lilypad install instructions (which versions) in our docs (at this point in time, both latest).

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad-docs#32]
Reference: https://github.com/Lilypad-Tech/lilypad-docs/issues/31#issuecomment-2068264634

**Comment by Zorlin** [comment]
Latest Lilypad (always) and Bacalhau v1.2.3 or v1.3.0 are correct.

1.2.3 works for sure, 1.3.0 appears to be working fine on Strawberry so I'm happy for us to support it

**Comment by galaxyxtwo** [comment]
@alvin-reyes @bgins this is done and can be reviewed. 

For context, with the current Lilypad network, we need to ensure that RPs are running Bacalhau 1.3.2. I have edited the docs to reflect this:

- updated the ["Bacalhau Install" guide](https://docs.lilypad.tech/lilypad/hardware-providers/run-a-node#install-bacalhau) in the ["Running a node" doc ](https://docs.lilypad.tech/lilypad/hardware-providers/run-a-node) with a disclaimer and command to check Bacalhau version. If they are running a later version than 1.3.2, they are directed to the troubleshooting page.
<img width="547" alt="Screenshot 2024-08-07 at 5 42 41 PM" src="https://github.com/user-attachments/assets/07cbcc41-5400-4999-9960-53ca3d16f56c">


- in the "Troubleshooting" section  added a step by step guide for [changing your bacalhau version to 1.3.2](https://docs.lilypad.tech/lilypad/hardware-providers/troubleshooting#how-do-i-change-my-bacalhau-version) 

<img width="572" alt="Screenshot 2024-08-07 at 5 42 58 PM" src="https://github.com/user-attachments/assets/b50e7df1-b9f4-40a3-836c-21ba0f181c21">

**Comment by bgins** [comment]
@galaxyxtwo looks good! When we add a Bacalhau version check to the binary, we can link to "How do I change my Bacalhau version".

One small detail. In the info hint in "Install Bacalhau", the second mention of the version should be `v1.3.2` instead of `v.1.3.2`. (remove extra period after the `v`)

**Comment by galaxyxtwo** [comment]
ah great catch thank you.

**Comment by galaxyxtwo** [comment]
Completed!
