### ISSUE TITLE
Review and delegate work for Running a Node in the Network

### ISSUE THREAD

**Issue by AquiGorka** [Lilypad-Tech/lilypad-docs#33]
Reference: https://docs.google.com/document/d/1XpGcSanAj1sjZNVQVLJ_C7P0V1-wXnVbv3DnsAhTHL8/edit#heading=h.58pwkjicckbc

Potentially we don't need a proper tutorial just yet (unless you think this is good to be published), this info is for us to have something in case somebody asks (in #help) or for now in one of our readmes.

You know what, as a minimum let's add this to the [Engineering Wiki](https://www.notion.so/lilypadnetwork/Wiki-index-fa1ed77f9c044785aa696e3f9cd9e64c) once it has been reviewed.

**Comment by developersteve** [comment]
Did a bunch of rewrite and edits to this one

**Comment by noryev** [comment]
Hardware requirements for Lilypad resource providers - [ ] 

Lilypad Services Setup (within Ubuntu) - [ ]
Devrel Prepared Material -[ ]
Operating System Setup Instructions (Dual Boot Setup) - [ ] 

Alternative OS instructions (Lilypad on Windows, Proxmox) TBD

**Comment by noryev** [comment]
video is sent to marketing team for editing: https://drive.google.com/file/d/1r_F1BWEmCdCDnJa6BDHMvowPMgskhzKJ/view?usp=drive_link
